
@baseUrl = http://localhost:80/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhbmVzaHJhbWFuLnJAZ21haWwuY29tIiwiaWF0IjoxNzMxNDgxMzgxLCJleHAiOjE3MzE1MTczODF9.Xw5L7kSgQTzeL0Fi8Xc8D1BorCDi1Sefgd3kZWWPEK0

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "ganeshraman.r@gmail.com",
    "password": "easy"
}

###
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "ganesh16@gmail.com",
    "password": "easy",
    "firstname": "A1",
    "lastname": "B1"
}

###
GET {{baseUrl}}/user/me
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/user/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "firstname": "GaneshMod",
    "lastname": "RamanMod"
}

###
GET http://localhost:80/api/openai/models
Authorization: Bearer {{token}}

###
GET http://localhost:80/api/openai/prompt
Authorization: Bearer {{token}}

###
GET https://api.openai.com/v1/models
Authorization: Bearer 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
'OpenAI-Organization': 'org-3v5B7uvTJcqvUAjzk3X72t0K'
'OpenAI-Project': 'proj_tzaXe5MRpS1c4DYyXNbfQCrq'

###
GET https://my-json-server.typicode.com/typicode/demo/posts